use super::*;

fn fixture(automatic:bool)->(Value,String,Value,String,Value){fixture_named(automatic,"")}
fn fixture_named(automatic:bool,prefix:&str)->(Value,String,Value,String,Value){
    let (mut d,run,profile,plan,result)=crate::preparation_review::chunks::r9_final_fixture(automatic,prefix);
    normalize(&mut d);
    d["audit"]=json!([{"id":"old-audit","action":"old-action","refId":format!("{prefix}i0"),"createdAt":crate::now()}]);
    d["approvals"]=json!([{"id":"old-approval","status":"approved","proposals":[],"context":{"private":"x".repeat(30_000)}}]);
    d["feedback"]=json!([{"id":"old-feedback","itemId":format!("{prefix}i0"),"text":"x".repeat(30_000)}]);
    d["conversations"]=json!([{"id":"old-private","messages":[{"text":"x".repeat(100_000)}]}]);
    crate::list_mut(&mut d,"jobs").push(json!({"id":"old-paid","kind":"assistant","purpose":"discussion",
        "status":"completed","result":{"paid":"x".repeat(100_000)}}));
    (d,run,profile,plan,result)
}
fn running_auto()->(Value,String,Value){
    let (mut d,run,_,_,result)=fixture(true);
    crate::row_mut(&mut d,"jobs",&run).unwrap()["status"]=json!("running");
    for item in d["items"].as_array_mut().unwrap(){item["autoPreparation"]["status"]=json!("running");item["autoPreparation"]["reviewResumeRequired"]=json!(false);}
    (d,run,result)
}
fn replace_generated_refs(value:&mut Value,ids:&std::collections::HashMap<String,String>){match value{
    Value::Object(object)=>for value in object.values_mut(){replace_generated_refs(value,ids);},
    Value::Array(array)=>for value in array{replace_generated_refs(value,ids);},
    Value::String(s)=>if let Some(id)=ids.get(s){*s=id.clone();},_=>(),
}}
fn final_value_hash(value:&Value)->String{
    use sha2::{Digest,Sha256};format!("{:x}",Sha256::digest(value.to_string().as_bytes()))
}
fn logical_eq(a:Value,b:Value){logical_eq_from(None,a,b);}
fn logical_eq_from(initial:Option<&Value>,a:Value,mut b:Value){
    // Verify each ORIGINAL document before canonicalizing generated output.
    // A wrong receipt/archive hash cannot be repaired by this comparison.
    for document in [&a,&b]{
        for job in crate::list(document,"jobs"){
            if !job["completedRecovery"].is_null(){
                assert_eq!(job["completedRecovery"]["version"],1);
                assert_eq!(job["status"],"completed");assert_eq!(job["result"],job["prepareOutcome"]);
                assert_eq!(job["completedRecovery"]["outcomeDigest"],final_value_hash(&job["prepareOutcome"]));
            }
        }
        for archive in document["preparationResearch"].as_array().into_iter().flatten(){
            if archive.get("checksum").is_some(){
                assert_eq!(archive["checksum"],crate::research_cache::checksum(archive));
            }
        }
    }
    // The existing engine reducer samples its review time internally. Normalize
    // only its generated archive/review clock, after proving those exact clocks
    // and review bodies belong to the same job. Source chronology is untouched.
    for (index,left) in a["preparationResearch"].as_array().into_iter().flatten().enumerate(){
        let right=&b["preparationResearch"][index];
        if left["createdAt"]!=right["createdAt"]{
            let run=left["jobId"].as_str().unwrap();
            let original=initial.expect("Clock normalization requires the original workspace");
            let old_job=crate::row(original,"jobs",run).unwrap();
            assert!(old_job["completedRecovery"].is_null());assert!(old_job["preparationStages"]["review"].is_null());
            assert!(!original["preparationResearch"].as_array().into_iter().flatten()
                .any(|archive|archive["id"]==left["id"]||archive["jobId"]==run),"Retained archive chronology is immutable");
            assert_eq!(right["jobId"],run);assert_eq!(left["id"],format!("research:{run}"));assert_eq!(left["id"],right["id"]);
            for (document,archive) in [(&a,left),(&b,right)]{
                let job=crate::row(document,"jobs",run).unwrap();
                assert_eq!(job["purpose"],"engine_prepare");assert!(job["completedRecovery"].is_object());
                assert_eq!(archive["checksum"],crate::research_cache::checksum(archive));
                assert_eq!(archive["review"],job["preparationStages"]["review"]);
                assert_eq!(archive["createdAt"],archive["review"]["at"]);
                chrono::DateTime::parse_from_rfc3339(archive["createdAt"].as_str().unwrap()).unwrap();
            }
            let at=left["createdAt"].clone();
            b["preparationResearch"][index]["createdAt"]=at.clone();
            b["preparationResearch"][index]["review"]["at"]=at.clone();
            crate::row_mut(&mut b,"jobs",run).unwrap()["preparationStages"]["review"]["at"]=at;
        }
    }
    // Only the new proposal/audit identities generated by paired reducers may
    // differ. Map by ordered output rows, preserving all references and their
    // relationships; a dangling/wrong reference cannot receive a mapping.
    let mut ids=std::collections::HashMap::new();
    for table in ["proposals","audit"]{
        assert_eq!(crate::list(&a,table).len(),crate::list(&b,table).len(),"{table}");
        for (index,left) in crate::list(&a,table).iter().enumerate(){
            let right=&mut b[table][index];
            if left["id"]!=right["id"]{
                let old=right["id"].as_str().unwrap();let expected=left["id"].as_str().unwrap();
                assert!(uuid::Uuid::parse_str(old).is_ok()&&uuid::Uuid::parse_str(expected).is_ok());
                assert!(ids.insert(old.to_owned(),expected.to_owned()).is_none());
                right["createdAt"]=left["createdAt"].clone();
            }
        }
    }
    replace_generated_refs(&mut b,&ids);
    // Derived hashes were verified against original bytes above. Recompute only
    // after deterministic identity/clock canonicalization for exact comparison.
    for job in b["jobs"].as_array_mut().unwrap(){
        if !job["completedRecovery"].is_null(){
            job["completedRecovery"]["outcomeDigest"]=json!(final_value_hash(&job["prepareOutcome"]));
        }
    }
    for archive in b.get_mut("preparationResearch").and_then(Value::as_array_mut).into_iter().flatten(){
        if archive.get("checksum").is_some(){archive["checksum"]=json!(crate::research_cache::checksum(archive));}
    }
    assert_eq!(a,b);
}
fn preserve(before:&Value,after:&Value,recovery:bool){
    for key in ["approvals","operations","feedback","conversations","posts","branches","materials","knowledge_entries","knowledge_versions"]{
        assert_eq!(before[key],after[key],"{key}");
    }
    assert_eq!(crate::row(before,"jobs","old-paid").unwrap(),crate::row(after,"jobs","old-paid").unwrap());
    let old=crate::list(before,"audit");let new=crate::list(after,"audit");
    assert!(new.starts_with(old));assert_eq!(new.len(),old.len()+usize::from(recovery));
}
fn assert_legacy_local_recovery(before:&Value,after:&Value,run:&str){
    let original=crate::row(before,"jobs",run).unwrap();
    let groups=original["preparationStages"]["groupAdmission"].as_array().unwrap();
    assert!(!groups.is_empty());assert!(groups.iter().all(|group|group["status"]=="pending"));
    assert!(crate::list(before,"proposals").iter().all(|p|p["prepareRunId"]!=run),"no original proposals for this pending capture");
    assert_ne!(original["prepareBundle"]["request"]["mandatoryMaterialContract"],crate::preparation_materials::CONTRACT,"genuine historical captured request");
    let created=crate::list(after,"proposals").iter().filter(|p|p["prepareRunId"]==run).collect::<Vec<_>>();
    assert!(!created.is_empty(),"reducer reached actual local proposal recovery");
    for proposal in created{
        assert_eq!(proposal["status"],"draft");
        assert_eq!(crate::proposal_current(after,proposal).unwrap_err().1,"legacy_material_contract_unmet","local recovery does not acquire new publication authority");
    }
    assert_eq!(after["approvals"],before["approvals"]);assert_eq!(after["operations"],before["operations"]);
    assert_eq!(crate::row(after,"jobs",run).unwrap()["prepareBundle"],original["prepareBundle"],"original capture bytes remain fixed");
    assert_eq!(crate::row(after,"jobs",run).unwrap()["preparationStages"]["first"],original["preparationStages"]["first"]);
}
fn simulate_scoped(initial:&Value,run:&str,intent:&Intent<'_>)->ApiResult<(Value,Value)>{
    let before=final_projection(initial,run)?;let mut after=before.clone();
    let (outcome,receipt)=intent.apply(&mut after,run)?;
    validate_final(&before,&after,run,intent.recovery())?;
    validate_audit_output(&before,&after,run,intent.recovery(),receipt.as_ref())?;
    let mut merged=initial.clone();merge_final(&mut merged,&before,&after,receipt.as_ref())?;
    Ok((merged,outcome))
}

#[test]
fn final_success_and_both_completed_recovery_reducers_match_full_workspace(){
    let (initial,run,result)=running_auto();let at=crate::now();
    let mut full=initial.clone();crate::auto_prepare::settle_success(&mut full,&run,&result,true,Some(&at)).unwrap();
    let (scoped,_)=simulate_scoped(&initial,&run,&Intent::Success{result:&result,reviewed:true,at:Some(&at)}).unwrap();
    preserve(&initial,&scoped,false);logical_eq(full,scoped);
    for automatic in [false,true]{
        let (initial,run,profile,plan,_)=fixture(automatic);let at=crate::now();
        let before=final_projection(&initial,&run).unwrap();
        for omitted in ["approvals","audit","feedback","conversations"]{assert!(before.get(omitted).is_none(),"{omitted}");}
        assert!(crate::row(&before,"jobs","old-paid").is_err());
        assert!(before.to_string().len()*5<initial.to_string().len());
        let mut full=initial.clone();crate::preparation_review::chunks::recover_in(&mut full,&run,&plan,&profile,&at).unwrap();
        let (scoped,_)=simulate_scoped(&initial,&run,&Intent::Recovery{plan:&plan,profile:&profile,at:&at}).unwrap();
        assert_legacy_local_recovery(&initial,&full,&run);assert_legacy_local_recovery(&initial,&scoped,&run);
        preserve(&initial,&scoped,true);logical_eq_from(Some(&initial),full,scoped);
    }
}

#[test]
fn returned_bridge_success_preserves_existing_stale_holds(){
    // Complete_initial's stale path is an Ok durable hold. Replacing broad
    // storage must not turn the hold into a discarded transaction.
    let (mut initial,run,result)=running_auto();initial["posts"][0]["text"]=json!("Changed source");
    let at=crate::now();let mut full=initial.clone();
    let expected=crate::auto_prepare::settle_success(&mut full,&run,&result,false,Some(&at)).unwrap();
    assert_eq!(expected["status"],"stale");
    let (scoped,outcome)=simulate_scoped(&initial,&run,&Intent::Success{result:&result,reviewed:false,at:Some(&at)}).unwrap();
    assert_eq!(outcome,expected);preserve(&initial,&scoped,false);logical_eq(full,scoped);
}

#[test]
fn singleton_stale_group_stale_held_and_already_admitted_members_preserve_full_behavior(){
    let (mut singleton,run,result)=crate::preparation_review::chunks::r9_final_singleton_fixture();normalize(&mut singleton);
    singleton["posts"][0]["text"]=json!("Changed singleton source");let at=crate::now();let mut full=singleton.clone();
    let outcome=crate::auto_prepare::settle_success(&mut full,&run,&result,false,Some(&at)).unwrap();assert_eq!(outcome["status"],"stale");
    let (scoped,_)=simulate_scoped(&singleton,&run,&Intent::Success{result:&result,reviewed:false,at:Some(&at)}).unwrap();logical_eq(full,scoped);
    for (hold,settled) in [(true,false),(false,true),(false,false)]{
        let (mut initial,run,result)=crate::preparation_review::chunks::r9_final_grouped_fixture(hold,settled);normalize(&mut initial);
        let prior=initial.clone();let mut full=initial.clone();let at=crate::now();
        let expected=crate::auto_prepare::settle_success(&mut full,&run,&result,true,Some(&at)).unwrap();
        let (scoped,outcome)=simulate_scoped(&initial,&run,&Intent::Success{result:&result,reviewed:true,at:Some(&at)}).unwrap();
        assert_eq!(outcome["status"],expected["status"]);logical_eq(scoped.clone(),full);
        if hold{assert!(crate::list(&scoped,"proposals").is_empty());assert_eq!(crate::row(&scoped,"jobs",&run).unwrap()["prepareOutcome"]["status"],"needs_attention");}
        if settled{
            assert_eq!(scoped["items"][0],prior["items"][0]);assert!(crate::list(&scoped,"proposals").starts_with(crate::list(&prior,"proposals")));
            let a=crate::row(&prior,"jobs",&run).unwrap()["preparationStages"]["groupAdmission"].as_array().unwrap().iter().find(|g|g["status"]=="admitted").unwrap();
            let b=crate::row(&scoped,"jobs",&run).unwrap()["preparationStages"]["groupAdmission"].as_array().unwrap().iter().find(|g|g["itemIds"]==a["itemIds"]).unwrap();assert_eq!(a,b);
        }
        if !hold&&!settled{
            // Unreviewed final reducer may preserve one group's stale hold and
            // another group's prepared result. No archive is fabricated.
            initial["posts"][1]["text"]=json!("Changed independent group source");let mut full=initial.clone();
            let expected=crate::auto_prepare::settle_success(&mut full,&run,&result,false,Some(&at)).unwrap();assert_eq!(expected["status"],"stale");
            let (scoped,outcome)=simulate_scoped(&initial,&run,&Intent::Success{result:&result,reviewed:false,at:Some(&at)}).unwrap();
            assert_eq!(outcome["status"],expected["status"]);logical_eq(scoped,full);
        }
    }
}

#[test]
fn final_delta_guard_rejects_capture_history_paid_attempt_and_retained_reference_changes(){
    let (initial,run,result)=running_auto();let at=crate::now();
    let before=final_projection(&initial,&run).unwrap();let mut good=before.clone();
    let (_,receipt)=Intent::Success{result:&result,reviewed:true,at:Some(&at)}.apply(&mut good,&run).unwrap();assert!(receipt.is_none());
    validate_final(&before,&good,&run,false).unwrap();
    for variant in ["approval","audit","feedback","operation","draft","source","company","connector","attempts","input","chunks","extra_job_field","proposal","other_job"]{
        let mut changed=good.clone();match variant{
            "approval"=>changed["approvals"]=json!([]),"audit"=>changed["audit"]=json!([]),"feedback"=>changed["feedback"]=json!([]),
            "operation"=>changed["operations"]=json!([{"id":"new","status":"unknown"}]),
            "draft"=>changed["items"][0]["draft"]=json!("Human text"),"source"=>changed["posts"][0]["text"]=json!("New source"),
            "company"=>changed["account"]=json!("BAW Russia"),"connector"=>changed["connectorBinding"]["provider"]=json!("native-other"),
            "attempts"=>changed["items"][0]["autoPreparation"]["attempts"]=json!(0),
            "input"=>changed["items"][0]["autoPreparation"]["inputDigest"]=json!("retargeted"),
            "chunks"=>crate::row_mut(&mut changed,"jobs",&run).unwrap()["preparationStages"]["reviewChunks"]["usage"]["chargedWebCalls"]=json!(0),
            "extra_job_field"=>crate::row_mut(&mut changed,"jobs",&run).unwrap()["unexpectedField"]=json!([]),
            "proposal"=>changed["proposals"][0]["status"]=json!("approved"),
            _=>crate::list_mut(&mut changed,"jobs").push(json!({"id":"extra","kind":"assistant","status":"running"})),
        }
        assert!(validate_final(&before,&changed,&run,false).is_err(),"{variant}");
    }
}

#[test]
fn final_archive_guard_preserves_existing_history_and_rejects_malformed_collections(){
    let (mut initial,run,result)=running_auto();let at=crate::now();
    // An unrelated unusable source-only archive is still retained history.
    // It does not alter the captured source selection or authorize admission.
    initial["preparationResearch"]=json!([{"id":"old-archive","jobId":"old-run","trust":"source_only","activePolicy":false}]);
    let before=final_projection(&initial,&run).unwrap();let mut good=before.clone();
    Intent::Success{result:&result,reviewed:true,at:Some(&at)}.apply(&mut good,&run).unwrap();
    validate_final(&before,&good,&run,false).unwrap();
    assert_eq!(good["preparationResearch"][0],initial["preparationResearch"][0]);
    for variant in ["deleted","truncated","malformed"]{
        let mut changed=good.clone();match variant{
            "deleted"=>{changed.as_object_mut().unwrap().remove("preparationResearch");},
            "truncated"=>{changed["preparationResearch"].as_array_mut().unwrap().remove(0);},
            _=>changed["preparationResearch"]=Value::Null,
        }
        assert!(validate_final(&before,&changed,&run,false).is_err(),"{variant}");
    }
    let mut malformed=before.clone();malformed["preparationResearch"]=json!({"not":"history"});
    assert!(validate_final(&malformed,&good,&run,false).is_err());
}

#[test]
fn recovery_exact_audit_output_and_noop_replay_contract(){
    let (initial,run,profile,plan,_)=fixture(false);let at=crate::now();
    let before=final_projection(&initial,&run).unwrap();let mut after=before.clone();
    let (_,receipt)=Intent::Recovery{plan:&plan,profile:&profile,at:&at}.apply(&mut after,&run).unwrap();let receipt=receipt.unwrap();
    assert_legacy_local_recovery(&before,&after,&run);
    validate_audit_output(&before,&after,&run,true,Some(&receipt)).unwrap();
    for variant in ["action","recipient","time","extra","missing"]{
        let mut forged=receipt.clone();match variant{
            "action"=>forged["action"]=json!("approval.created"),"recipient"=>forged["refId"]=json!("other-run"),
            "time"=>forged["createdAt"]=json!("not-a-time"),"extra"=>forged["authority"]=json!(true),_=>(),
        }
        assert!(validate_audit_output(&before,&after,&run,true,if variant=="missing"{None}else{Some(&forged)}).is_err(),"{variant}");
    }
    let (replayed,receipt)=Intent::Recovery{plan:&plan,profile:&profile,at:&at}.apply(&mut after,&run).unwrap();assert!(receipt.is_none());
    assert_eq!(replayed,crate::row(&after,"jobs",&run).unwrap()["prepareOutcome"]);
    validate_audit_output(&after,&after,&run,true,None).unwrap();
}

// Each scenario captures its own namespaced recipients BEFORE the paid request
// is hashed. Append fixtures to the selector-owned database; never erase PG
// history to reset a hostile scenario. The shared cold history is seeded once.
fn merge_final_scenario(d:&mut Value,scenario:Value){
    if crate::list(d,"items").is_empty(){*d=scenario;}
    else{
        assert_eq!(d["account"],scenario["account"]);
        assert_eq!(d["connectorBinding"],scenario["connectorBinding"]);
        for key in ["items","posts","branches","proposals","operations","jobs"]{
            for row in crate::list(&scenario,key){
                if key=="jobs"&&row["id"]=="old-paid"{continue;}
                assert!(!crate::list(d,key).iter().any(|old|old["id"]==row["id"]),"fresh namespaced row: {key}");
                crate::list_mut(d,key).push(row.clone());
            }
        }
    }
}
async fn append_final_scenario(db:&Database,scenario:Value){
    db.change(|d|{merge_final_scenario(d,scenario);Ok(())}).await.unwrap();
}
async fn exercise_storage(db:&Database,automatic:bool){
    // Every hostile fixture is committed BEFORE scoped storage captures it.
    // Compare the full reducer's decision with the connected scoped decision.
    for (index,variant) in ["plan","profile","source","media","approval","approval_dispatching","approval_unknown","unknown","human","cancelled","unknown_attempt","usage"].into_iter().enumerate(){
        let prefix=format!("r9-final-{automatic}-{index}-");
        let (mut mutated,run,profile,plan,_)=fixture_named(automatic,&prefix);let at=crate::now();
        let item_id=format!("{prefix}i1");
        // Prove retained earlier hostile history does not mask this scenario's
        // original fence. This pristine positive control is never persisted.
        let mut clean=db.read().await.unwrap();merge_final_scenario(&mut clean,mutated.clone());
        assert!(crate::preparation_review::chunks::recover_in(&mut clean,&run,&plan,&profile,&at).is_ok(),"pristine namespace must recover before hostile mutation: {automatic} {variant}");
        let mut current_profile=profile.clone();let mut current_plan=plan.clone();
        match variant{
            "plan"=>current_plan="0".repeat(64),"profile"=>current_profile["runtimeSha256"]=json!("0".repeat(64)),
            "source"=>mutated["posts"][0]["text"]=json!("Changed live source"),
            "media"=>mutated["posts"][0]["attachments"]=json!([{"type":"video","url":"https://fixture.invalid/changed.mp4"}]),
            "approval"|"approval_dispatching"|"approval_unknown"=>mutated["proposals"]=json!([{"id":format!("{prefix}approved-target"),"itemId":item_id,
                "status":match variant{"approval"=>"approved","approval_dispatching"=>"dispatching",_=>"unknown"}}]),
            "unknown"=>mutated["operations"]=json!([{"id":format!("{prefix}uncertain"),"itemId":item_id,"status":"unknown","target":mutated["items"][1]}]),
            "human"=>{mutated["items"][1]["draft"]=json!("Operator text");mutated["items"][1]["draftEdited"]=json!(true);},
            "cancelled"=>crate::row_mut(&mut mutated,"jobs",&run).unwrap()["status"]=json!("cancelled"),
            "unknown_attempt"=>crate::row_mut(&mut mutated,"jobs",&run).unwrap()["preparationStages"]["reviewChunks"]["chunks"][0]["attempts"][0]["status"]=json!("unknown"),
            _=>crate::row_mut(&mut mutated,"jobs",&run).unwrap()["preparationStages"]["reviewChunks"]["usage"]["chargedWebCalls"]=json!(0),
        }
        append_final_scenario(db,mutated).await;let before=db.read().await.unwrap();let mut full=before.clone();
        let expected=crate::preparation_review::chunks::recover_in(&mut full,&run,&current_plan,&current_profile,&at);
        assert!(expected.is_err(),"hostile input must engage its fence: {automatic} {variant}");
        assert!(db.change_preparation_final(&run,Intent::Recovery{plan:&current_plan,profile:&current_profile,at:&at},None).await.is_err(),"{variant}");
        assert_eq!(db.read().await.unwrap(),before,"exact rollback: {variant}");
    }
    let prefix=format!("r9-final-{automatic}-success-");
    let (initial,run,profile,plan,_)=fixture_named(automatic,&prefix);let at=crate::now();
    append_final_scenario(db,initial).await;let original=db.read().await.unwrap();
    let retained=crate::row(&original,"jobs",&run).unwrap()["preparationStages"]["reviewChunks"].clone();
    let mut full=original.clone();let expected=crate::preparation_review::chunks::recover_in(&mut full,&run,&plan,&profile,&at).unwrap();
    let (outcome,changed)=db.change_preparation_final(&run,Intent::Recovery{plan:&plan,profile:&profile,at:&at},None).await.unwrap();
    assert!(changed);assert_eq!(outcome["status"],expected["status"]);let saved=db.read().await.unwrap();preserve(&original,&saved,true);logical_eq_from(Some(&original),saved.clone(),full);
    assert_legacy_local_recovery(&original,&saved,&run);
    assert_eq!(crate::row(&saved,"jobs",&run).unwrap()["preparationStages"]["reviewChunks"],retained);
    let (replay,changed)=db.change_preparation_final(&run,Intent::Recovery{plan:&plan,profile:&profile,at:&at},None).await.unwrap();
    assert!(!changed);assert_eq!(replay,outcome);assert_eq!(db.read().await.unwrap(),saved);
    // A committed recovery is a receipt replay even if its resulting proposal
    // has since been approved. It may neither readmit nor erase that decision.
    let proposal_id=crate::list(&saved,"proposals").iter().find(|p|p["prepareRunId"]==run).unwrap()["id"].as_str().unwrap().to_owned();
    db.change(|d|{crate::row_mut(d,"proposals",&proposal_id)?["status"]=json!("approved");Ok(())}).await.unwrap();
    let approved=db.read().await.unwrap();
    let (replay,changed)=db.change_preparation_final(&run,Intent::Recovery{plan:&plan,profile:&profile,at:&at},None).await.unwrap();
    assert!(!changed);assert_eq!(replay,outcome);assert_eq!(db.read().await.unwrap(),approved);
    // The legacy running reservation is last: its synthetic row and captured
    // bundle stay durable, with no deletion, cancellation or reset cleanup.
    let (mut reserved,reserved_run,reserved_profile,reserved_plan,_)=fixture_named(automatic,&format!("r9-final-{automatic}-reservation-"));
    let mut clean=db.read().await.unwrap();merge_final_scenario(&mut clean,reserved.clone());let at=crate::now();
    assert!(crate::preparation_review::chunks::recover_in(&mut clean,&reserved_run,&reserved_plan,&reserved_profile,&at).is_ok(),"pristine namespace must recover before hostile mutation: {automatic} reservation");
    let bundle=crate::row(&reserved,"jobs",&reserved_run).unwrap()["prepareBundle"].clone();
    crate::list_mut(&mut reserved,"jobs").push(json!({"id":format!("r9-final-{automatic}-other-owner"),"kind":"assistant","purpose":"engine_prepare","status":"running","prepareBundle":bundle}));
    append_final_scenario(db,reserved).await;let before=db.read().await.unwrap();let mut full=before.clone();let at=crate::now();
    assert!(crate::preparation_review::chunks::recover_in(&mut full,&reserved_run,&reserved_plan,&reserved_profile,&at).is_err(),"hostile input must engage its fence: {automatic} reservation");
    assert!(db.change_preparation_final(&reserved_run,Intent::Recovery{plan:&reserved_plan,profile:&reserved_profile,at:&at},None).await.is_err(),"reservation");
    assert_eq!(db.read().await.unwrap(),before,"exact rollback: reservation");
}

async fn exercise_rule_fence(db:&Database){
    let (mut initial,run,profile,plan,_)=fixture(true);let at=crate::now();
    // A real current manual rule advances the catalog after the paid capture.
    // Seed this in a fresh fixture: immutable knowledge versions are never
    // deleted/reset to manufacture the next scenario.
    crate::knowledge::save_instruction(&mut initial,&json!({"requestId":"r9-current-rule","title":"Current rule","text":"New exact company rule after capture"}),&at).unwrap();
    db.change(|d|{*d=initial;Ok(())}).await.unwrap();let before=db.read().await.unwrap();let mut full=before.clone();
    assert!(crate::preparation_review::chunks::recover_in(&mut full,&run,&plan,&profile,&at).is_err());
    assert!(db.change_preparation_final(&run,Intent::Recovery{plan:&plan,profile:&profile,at:&at},None).await.is_err());
    assert_eq!(db.read().await.unwrap(),before);
}

#[tokio::test]
async fn sqlite_current_rule_is_recaptured_inside_final_storage(){
    let folder=tempfile::tempdir().unwrap();let db=Database::Sqlite(crate::open_db(&folder.path().join("r9-rule.sqlite")).await.unwrap());
    exercise_rule_fence(&db).await;db.close().await;
}

#[tokio::test]
async fn sqlite_both_completed_recoveries_keep_atomic_receipt_and_restart_replay(){
    for automatic in [false,true]{
        let folder=tempfile::tempdir().unwrap();let path=folder.path().join("r9-final.sqlite");
        let db=Database::Sqlite(crate::open_db(&path).await.unwrap());exercise_storage(&db,automatic).await;
        let saved=db.read().await.unwrap();db.close().await;
        let reopened=Database::Sqlite(crate::open_db(&path).await.unwrap());assert_eq!(reopened.read().await.unwrap(),saved);
        let run=crate::list(&saved,"jobs").iter().find(|j|j["completedRecovery"].is_object()).unwrap()["id"].as_str().unwrap();
        let job=crate::row(&saved,"jobs",run).unwrap();
        let (_,changed)=reopened.change_preparation_final(run,Intent::Recovery{plan:job["completedRecovery"]["planDigest"].as_str().unwrap(),
            profile:&job["preparationStages"]["reviewChunks"]["profile"],at:&crate::now()},None).await.unwrap();
        assert!(!changed);assert_eq!(reopened.read().await.unwrap(),saved);reopened.close().await;
    }
}

#[tokio::test]
async fn sqlite_success_stale_hold_and_late_review_error_are_atomic(){
    let folder=tempfile::tempdir().unwrap();let db=Database::Sqlite(crate::open_db(&folder.path().join("r9-success.sqlite")).await.unwrap());
    let (mut initial,run,result)=running_auto();
    initial["preparationResearch"]=json!([{"id":"duplicate-archive","jobId":run,"trust":"source_only","activePolicy":false}]);
    // An unusable source-only archive does not enter source selection, but its
    // job identity must engage record_review's duplicate check AFTER admission.
    let mut admission_probe=initial.clone();
    assert!(crate::auto_prepare::complete(&mut admission_probe,&run,&result,chrono::Utc::now().timestamp()).is_ok());
    assert!(!crate::list(&admission_probe,"proposals").is_empty(),"late-failure fixture actually admits proposals first");
    db.change(|d|{*d=initial;Ok(())}).await.unwrap();let before=db.read().await.unwrap();
    let error=db.change_preparation_final(&run,Intent::Success{result:&result,reviewed:true,at:Some(&crate::now())},None).await.unwrap_err();
    assert_eq!(error.1,"Research archive already exists","exact late gate");
    assert_eq!(db.read().await.unwrap(),before);
    db.change(|d|{d["posts"][0]["text"]=json!("Stale source");Ok(())}).await.unwrap();let before=db.read().await.unwrap();
    let mut full=before.clone();let at=crate::now();let expected=crate::auto_prepare::settle_success(&mut full,&run,&result,false,Some(&at)).unwrap();
    let (outcome,changed)=db.change_preparation_final(&run,Intent::Success{result:&result,reviewed:false,at:Some(&at)},None).await.unwrap();
    assert!(changed);assert_eq!(outcome,expected);logical_eq(db.read().await.unwrap(),full);db.close().await;
}

#[tokio::test]
async fn app_final_settlement_allows_drain_completion_but_rejects_changed_runtime_owner(){
    let (mut app,_folder)=crate::tests::test_app().await;let (mut initial,run,result)=running_auto();
    app.db.change(|d|{initial["runtimeLifecycle"]=d["runtimeLifecycle"].clone();*d=initial;Ok(())}).await.unwrap();
    let original_owner=app.lifecycle_owner.clone();let mut foreign=(*original_owner).clone();foreign.runtime_id="other-r9-runtime".into();
    app.lifecycle_owner=std::sync::Arc::new(foreign);let before=app.db.read().await.unwrap();
    assert!(app.settle_preparation_success(&run,&result,true).await.is_err());assert_eq!(app.db.read().await.unwrap(),before);
    app.lifecycle_owner=original_owner;
    app.db.change_runtime_lifecycle_with_ledger(|d|{
        let token=crate::runtime_lifecycle::bound_admission_token(d,&app.lifecycle_owner,crate::runtime_lifecycle::AdmissionClass::Preparation)?;
        crate::runtime_lifecycle::begin_drain(d,&token,&"c".repeat(64),"r9-final-drain",true).map(|_|())
    }).await.unwrap();
    let before=app.db.read().await.unwrap();let outcome=app.settle_preparation_success(&run,&result,true).await.unwrap();
    assert_eq!(outcome["status"],"prepared");let saved=app.db.read().await.unwrap();
    assert_eq!(saved["runtimeLifecycle"],before["runtimeLifecycle"],"settlement creates no new admission or lifecycle transition");
    preserve(&before,&saved,false);assert_eq!(crate::list(&saved,"jobs").len(),crate::list(&before,"jobs").len());
}

fn real_paid_capture(store:&crate::media_artifacts::ArtifactStore,d:&mut Value,run:&str,response:&Value)
    ->(Value,crate::media_artifacts::ArtifactRef,Vec<u8>){
    use sha2::{Digest,Sha256};
    let request=crate::row(d,"jobs",run).unwrap()["prepareBundle"]["request"].clone();
    let paid_item=crate::row(d,"jobs",run).unwrap()["prepareBundle"]["itemIds"][0].clone();
    let hash=|value:&Value|format!("{:x}",Sha256::digest(value.to_string().as_bytes()));
    // R1's complete capture and pointer schema, backed by a real private temp
    // CAS object. A historical runtime owner remains observation-only.
    let record=json!({"version":2,"kind":"retained-native-paid-stage-result","company":"likeavto","account":"LikeAvto",
        "runtimeOwner":{"account":"LikeAvto","runtimeId":"r9-paid-fixture-owner","releaseSha256":"a".repeat(64)},
        "binding":{"nativeJobId":run,"operation":"assistant","itemId":paid_item},
        "requestSha256":hash(&request),"responseSha256":hash(response),"request":request,"response":response,
        "retryAuthorized":false,"dispatchAuthorized":false});
    let bytes=record.to_string().into_bytes();let artifact=store.put_bytes(&bytes).unwrap();
    let reference=json!({"version":1,"kind":"native-paid-capture-ref","company":record["company"],"account":record["account"],
        "binding":record["binding"],"runtimeOwner":record["runtimeOwner"],"requestSha256":record["requestSha256"],
        "responseSha256":record["responseSha256"],"artifact":artifact.to_json(),"retryAuthorized":false,"dispatchAuthorized":false});
    assert_eq!(crate::runtime_paid_result::resolve_from(store,"likeavto","LikeAvto",Some(run),"assistant",&reference).unwrap(),record);
    let before=d.clone();crate::row_mut(d,"jobs",run).unwrap()["retainedEvidence"]=json!([reference]);
    crate::runtime_paid_result::validate_change(&before,d).unwrap();
    (record,artifact,bytes)
}

#[tokio::test]
async fn sqlite_real_retained_evidence_survives_scoped_success_recovery_restart_and_fault_rollback(){
    for scenario in ["success","engine_recovery","auto_recovery"]{
        let folder=tempfile::tempdir().unwrap();let path=folder.path().join("r9-paid-final.sqlite");let cas=folder.path().join("private-paid-cas");
        let store=crate::media_artifacts::ArtifactStore::open(&cas).unwrap();
        let (mut initial,run,profile,plan,result)=if scenario=="success"{
            let (d,run,result)=running_auto();(d,run,Value::Null,String::new(),result)
        }else{fixture(scenario=="auto_recovery")};
        let (record,artifact,bytes)=real_paid_capture(&store,&mut initial,&run,&result);
        let original_refs=crate::row(&initial,"jobs",&run).unwrap()["retainedEvidence"].clone();
        let db=Database::Sqlite(crate::open_db(&path).await.unwrap());db.change(|d|{*d=initial;Ok(())}).await.unwrap();
        let before=db.read().await.unwrap();let at=crate::now();
        if scenario!="success"{
            let mut positive=before.clone();crate::preparation_review::chunks::recover_in(&mut positive,&run,&plan,&profile,&at).unwrap();
            assert_legacy_local_recovery(&before,&positive,&run);
        }
        for rebind in [false,true]{
            let original_intent=if scenario=="success"{Intent::Success{result:&result,reviewed:true,at:Some(&at)}}
                else{Intent::Recovery{plan:&plan,profile:&profile,at:&at}};
            let error=db.change_preparation_final(&run,Intent::PaidFault{intent:Box::new(original_intent),rebind},None).await.unwrap_err();
            assert!(error.1.contains("immutable job capture"),"actual final scope catches post-reducer paid fault: {scenario} {rebind}: {}",error.1);
            assert_eq!(db.read().await.unwrap(),before,"entire scoped transaction rolls back: {scenario} {rebind}");
            assert_eq!(store.read_bytes(&artifact,128*1024*1024).unwrap(),bytes);
            assert_eq!(crate::runtime_paid_result::resolve_from(&store,"likeavto","LikeAvto",Some(&run),"assistant",&original_refs[0]).unwrap(),record);
        }
        let intent=if scenario=="success"{Intent::Success{result:&result,reviewed:true,at:Some(&at)}}
            else{Intent::Recovery{plan:&plan,profile:&profile,at:&at}};
        let (_,changed)=db.change_preparation_final(&run,intent,None).await.unwrap();assert!(changed);
        let saved=db.read().await.unwrap();assert_eq!(crate::row(&saved,"jobs",&run).unwrap()["retainedEvidence"],original_refs);
        if scenario!="success"{assert_legacy_local_recovery(&before,&saved,&run);}
        preserve(&before,&saved,scenario!="success");assert_eq!(store.read_bytes(&artifact,128*1024*1024).unwrap(),bytes);
        db.close().await;drop(store);
        let reopened=Database::Sqlite(crate::open_db(&path).await.unwrap());assert_eq!(reopened.read().await.unwrap(),saved);
        let reopened_store=crate::media_artifacts::ArtifactStore::open(&cas).unwrap();
        assert_eq!(reopened_store.read_bytes(&artifact,128*1024*1024).unwrap(),bytes);
        assert_eq!(crate::runtime_paid_result::resolve_from(&reopened_store,"likeavto","LikeAvto",Some(&run),"assistant",
            &crate::row(&reopened.read().await.unwrap(),"jobs",&run).unwrap()["retainedEvidence"][0]).unwrap(),record);
        reopened.close().await;
    }
}

#[tokio::test]
#[ignore="requires a pristine explicitly isolated communityhero_writer_v51_test_ PostgreSQL fixture"]
async fn postgres_real_retained_evidence_survives_scoped_recovery_and_fault_rollback(){
    let folder=tempfile::tempdir().unwrap();let cas=folder.path().join("private-paid-cas");
    let store=crate::media_artifacts::ArtifactStore::open(&cas).unwrap();
    let (mut initial,run,profile,plan,result)=fixture(true);
    let (record,artifact,bytes)=real_paid_capture(&store,&mut initial,&run,&result);
    let original_refs=crate::row(&initial,"jobs",&run).unwrap()["retainedEvidence"].clone();
    let db=writer_v51_fixture_db().await;db.change(|d|{*d=initial;Ok(())}).await.unwrap();
    let before=db.read().await.unwrap();let at=crate::now();
    for rebind in [false,true]{
        let intent=Intent::Recovery{plan:&plan,profile:&profile,at:&at};
        let error=db.change_preparation_final(&run,Intent::PaidFault{intent:Box::new(intent),rebind},None).await.unwrap_err();
        assert!(error.1.contains("immutable job capture"),"actual PG final scope rejects paid fault: {rebind}: {}",error.1);
        assert_eq!(db.read().await.unwrap(),before,"PG scoped transaction rolls back the full durable ledger");
        assert_eq!(store.read_bytes(&artifact,128*1024*1024).unwrap(),bytes);
        assert_eq!(crate::runtime_paid_result::resolve_from(&store,"likeavto","LikeAvto",Some(&run),"assistant",&original_refs[0]).unwrap(),record);
    }
    let mut full=before.clone();crate::preparation_review::chunks::recover_in(&mut full,&run,&plan,&profile,&at).unwrap();
    assert_legacy_local_recovery(&before,&full,&run);
    let (_,changed)=db.change_preparation_final(&run,Intent::Recovery{plan:&plan,profile:&profile,at:&at},None).await.unwrap();assert!(changed);
    let saved=db.read().await.unwrap();assert_eq!(crate::row(&saved,"jobs",&run).unwrap()["retainedEvidence"],original_refs);
    preserve(&before,&saved,true);logical_eq(full,saved.clone());
    let (_,changed)=db.change_preparation_final(&run,Intent::Recovery{plan:&plan,profile:&profile,at:&at},None).await.unwrap();assert!(!changed);
    assert_eq!(db.read().await.unwrap(),saved);db.close().await;drop(store);
    let reopened=crate::media_artifacts::ArtifactStore::open(&cas).unwrap();
    assert_eq!(reopened.read_bytes(&artifact,128*1024*1024).unwrap(),bytes);
    assert_eq!(crate::runtime_paid_result::resolve_from(&reopened,"likeavto","LikeAvto",Some(&run),"assistant",&original_refs[0]).unwrap(),record);
}

#[tokio::test]
#[ignore="requires a pristine explicitly isolated communityhero_writer_v51_test_ PostgreSQL fixture"]
async fn postgres_engine_completed_recovery_full_parity(){
    let db=writer_v51_fixture_db().await;exercise_storage(&db,false).await;db.close().await;
}
#[tokio::test]
#[ignore="requires a pristine explicitly isolated communityhero_writer_v51_test_ PostgreSQL fixture"]
async fn postgres_auto_completed_recovery_full_parity(){
    let db=writer_v51_fixture_db().await;exercise_storage(&db,true).await;db.close().await;
}
#[tokio::test]
#[ignore="requires a pristine explicitly isolated communityhero_writer_v51_test_ PostgreSQL fixture"]
async fn postgres_current_rule_final_storage_fence(){
    let db=writer_v51_fixture_db().await;exercise_rule_fence(&db).await;db.close().await;
}
#[tokio::test]
#[ignore="requires a pristine explicitly isolated communityhero_writer_v51_test_ PostgreSQL fixture"]
async fn postgres_final_audit_insert_failure_rolls_back_item_proposal_job_archive(){
    let db=writer_v51_fixture_db().await;let (initial,run,profile,plan,_)=fixture(true);
    db.change(|d|{*d=initial;Ok(())}).await.unwrap();let before=db.read().await.unwrap();
    let Database::Postgres{writer,..}=&db else{unreachable!()};
    sqlx::query("CREATE FUNCTION pg_temp.r9_final_reject() RETURNS trigger LANGUAGE plpgsql AS 'BEGIN RAISE EXCEPTION ''synthetic final audit insertion rejection''; END;'")
        .execute(writer).await.unwrap();
    sqlx::query("CREATE TRIGGER r9_final_reject BEFORE INSERT ON communityhero.audit FOR EACH ROW EXECUTE FUNCTION pg_temp.r9_final_reject()")
        .execute(writer).await.unwrap();
    assert!(db.change_preparation_final(&run,Intent::Recovery{plan:&plan,profile:&profile,at:&crate::now()},None).await.is_err());
    assert_eq!(db.read().await.unwrap(),before,"late SQL failure rolls back the entire final settlement");db.close().await;
}

// Finite R3 workload: production App writers, isolated PG fixtures and private
// CAS only. Set both explicitly named fixture URLs/databases before selecting.
fn r3_workload_parity(left:Value,right:Value){
    // Shared comparator now proves BOTH original receipt/archive hashes before
    // canonicalizing generated UUIDs. Do not overwrite either original digest.
    logical_eq(left,right);
}
fn r3_numeric_metrics(events:&[Value],scoped:bool)->Value{
    let stage=if scoped{"preparation.projection.materialized"}else{"workspace.projection.materialized"};
    let materialized:Vec<_>=events.iter().filter(|e|e["stage"]==stage).collect();
    assert_eq!(materialized.len(),1,"one actual reducer projection per measured writer");
    let held=if scoped{"preparation.final.writer.held"}else{"workspace.writer.held"};
    let held:Vec<_>=events.iter().filter(|e|e["stage"]==held).collect();assert_eq!(held.len(),1);
    let calls=|stage:&str|events.iter().filter(|e|e["stage"]==stage).count();
    let controls:Vec<_>=events.iter().filter(|e|e["stage"]=="r3.scope.controls.materialized").map(|e|e["work"].clone()).collect();
    assert!(calls("r3.sql.read")>0,"actual SQL probe must be integrated");
    json!({"materialized":materialized[0]["work"],"controls":controls,"sqlReads":calls("r3.sql.read"),
        "sqlWrites":calls("r3.sql.write"),"writerHeldMs":held[0]["elapsedMs"],
        "sqlScope":"successful application statements; excludes SQLx BEGIN/COMMIT/connection initialization",
        "byteScope":"raw selected PG JSON text plus metadata; controls separate; not physical TOAST/index/bloat"})
}
fn r3_grow_history(d:&mut Value,from:usize,to:usize,at:&str){
    for n in from..to{
        crate::list_mut(d,"jobs").push(json!({"id":format!("r3-history-paid-{n}"),"kind":"assistant","purpose":"discussion",
            "status":"completed","request":{"input":"q".repeat(512)},"result":{"paid":"p".repeat(1536)},"retryAuthorized":false}));
        crate::list_mut(d,"feedback").push(json!({"id":format!("r3-history-feedback-{n}"),"itemId":"r3-history-item",
            "text":"f".repeat(2048)}));
        crate::list_mut(d,"approvals").push(json!({"id":format!("r3-history-approval-{n}"),"status":"approved","proposals":[],
            "context":{"private":"a".repeat(1024)}}));
        crate::list_mut(d,"conversations").push(json!({"id":format!("r3-history-conversation-{n}"),
            "messages":[{"text":"c".repeat(1024)}]}));
        crate::list_mut(d,"audit").push(json!({"id":format!("r3-history-audit-{n}"),"action":"r3.synthetic_history",
            "refId":"unrelated","createdAt":at,"details":"h".repeat(256)}));
    }
}
#[tokio::test]
#[ignore="finite R3 workload; requires TWO pristine explicitly isolated communityhero_writer_v51_test_ PostgreSQL databases"]
async fn postgres_r3_final_recovery_workload_100_1000_5000_actual_app_pair(){
    let scoped_url=std::env::var("COMMUNITYHERO_R3_SCOPED_TEST_URL").expect("explicit second isolated fixture URL");
    let scoped_name=std::env::var("COMMUNITYHERO_R3_SCOPED_TEST_DATABASE").expect("explicit second isolated fixture name");
    let broad_name=std::env::var("COMMUNITYHERO_WRITER_V51_TEST_DATABASE").unwrap();
    assert_ne!(broad_name,scoped_name,"pair must never share a writer/history");
    let (mut broad,_broad_folder)=crate::tests::test_app().await;
    let (mut scoped,_scoped_folder)=crate::tests::test_app().await;
    broad.db.close().await;scoped.db.close().await;
    broad.db=writer_v51_fixture_db().await;
    scoped.db=super::super::writer_v51_fixture_db_with(&scoped_url,&scoped_name).await;
    crate::runtime_lifecycle_app::initialize_app_fixture(&broad).await.unwrap();
    crate::runtime_lifecycle_app::initialize_app_fixture(&scoped).await.unwrap();
    let cas_folder=tempfile::tempdir().unwrap();let cas=cas_folder.path().join("private-paid-cas");
    let store=crate::media_artifacts::ArtifactStore::open(&cas).unwrap();
    let mut previous=0;let mut reports=Vec::new();let mut captures=Vec::new();
    for size in [100usize,1000,5000]{
        let (mut target,run,profile,plan,result)=crate::preparation_review::chunks::r9_final_workload_fixture(&format!("r3-{size}-"));
        normalize(&mut target);let at=crate::now();
        let historical=fixture(true).0;
        for key in ["approvals","audit","feedback","conversations"]{target[key]=historical[key].clone();}
        crate::list_mut(&mut target,"jobs").push(crate::row(&historical,"jobs","old-paid").unwrap().clone());
        // Native PG invariants apply to synthetic history too. This distinct
        // item keeps feedback outside the current recipients without dangling
        // references; empty approval proposal lists remain immutable history.
        if previous==0{crate::list_mut(&mut target,"items").push(json!({"id":"r3-history-item","revision":1,"workflow":"done"}));}
        target["approvals"][0]["proposals"]=json!([]);
        target["feedback"][0]["itemId"]=json!("r3-history-item");
        let (record,artifact,bytes)=real_paid_capture(&store,&mut target,&run,&result);
        let target_job=crate::row(&target,"jobs",&run).unwrap().clone();
        for app in [&broad,&scoped]{
            app.db.change(|d|{
                // Only setup: independently namespaced recipients/routes were
                // created BEFORE paid capture. Append current source and keep
                // every predecessor item, proposal and immutable paid record.
                for key in ["items","posts","branches"]{
                    crate::list_mut(d,key).extend_from_slice(crate::list(&target,key));
                }
                if previous==0{
                    for key in ["operations","materials","knowledge_entries","knowledge_versions"]{d[key]=target[key].clone();}
                    for key in ["approvals","audit","feedback","conversations"]{d[key]=target[key].clone();}
                    crate::list_mut(d,"jobs").push(crate::row(&target,"jobs","old-paid").unwrap().clone());
                }
                crate::list_mut(d,"jobs").push(target_job.clone());r3_grow_history(d,previous,size,&at);Ok(())
            }).await.unwrap();
        }
        let broad_before=broad.db.read().await.unwrap();let scoped_before=scoped.db.read().await.unwrap();
        r3_workload_parity(broad_before.clone(),scoped_before.clone());
        assert_eq!(crate::row(&broad_before,"jobs",&run).unwrap(),crate::row(&scoped_before,"jobs",&run).unwrap(),"exact current target paid input");
        let input_bytes=broad_before.to_string().len();
        if size==5000{assert!((10*1024*1024..=50*1024*1024).contains(&input_bytes),"bounded meaningful synthetic payload");}
        let (broad_outcome,broad_events)=crate::performance::capture(broad.change(|d|{
            crate::preparation_review::chunks::recover_in(d,&run,&plan,&profile,&at)
        })).await;let broad_outcome=broad_outcome.unwrap();
        let (scoped_outcome,scoped_events)=crate::performance::capture(scoped.recover_completed_preparation(&run,&plan,&profile,&at)).await;
        let (scoped_outcome,changed)=scoped_outcome.unwrap();assert!(changed);
        assert_eq!(broad_outcome["status"],scoped_outcome["status"]);
        // ALL full readback/parity, CAS resolution and restart verification are
        // outside performance::capture and therefore outside measured spans.
        let broad_saved=broad.db.read().await.unwrap();let scoped_saved=scoped.db.read().await.unwrap();
        preserve(&broad_before,&broad_saved,true);preserve(&scoped_before,&scoped_saved,true);
        r3_workload_parity(broad_saved.clone(),scoped_saved.clone());
        for (before,saved) in [(&broad_before,&broad_saved),(&scoped_before,&scoped_saved)]{
            assert_eq!(crate::row(before,"jobs",&run).unwrap()["preparationStages"]["reviewChunks"],
                crate::row(saved,"jobs",&run).unwrap()["preparationStages"]["reviewChunks"]);
            for job in crate::list(before,"jobs").iter().filter(|job|job["id"]!=run){
                assert_eq!(job,crate::row(saved,"jobs",job["id"].as_str().unwrap()).unwrap());
            }
            assert_eq!(crate::row(saved,"jobs",&run).unwrap()["retainedEvidence"],target_job["retainedEvidence"]);
            assert_eq!(crate::runtime_paid_result::resolve_from(&store,"likeavto","LikeAvto",Some(&run),"assistant",
                &crate::row(saved,"jobs",&run).unwrap()["retainedEvidence"][0]).unwrap(),record);
        }
        let full=r3_numeric_metrics(&broad_events,false);let narrow=r3_numeric_metrics(&scoped_events,true);
        assert!(full["materialized"]["rows"].as_u64().unwrap()>narrow["materialized"]["rows"].as_u64().unwrap());
        assert!(full["materialized"]["bytes"].as_u64().unwrap()>narrow["materialized"]["bytes"].as_u64().unwrap());
        reports.push(json!({"unrelatedRowsPerCollection":size,"fixtureLogicalSerializedBytes":input_bytes,
            "observedSelectedByteRatio":full["materialized"]["bytes"].as_u64().unwrap() as f64/narrow["materialized"]["bytes"].as_u64().unwrap() as f64,
            "scenario":"auto completed paid recovery","broad":full,"scoped":narrow,
            "inputParity":"exact current paid job/request/result; complete workspace logical UUID parity",
            "postcommitFullReadbackOutsideMeasurement":true}));
        captures.push((run,record,artifact,bytes));previous=size;
    }
    let broad_saved=broad.db.read().await.unwrap();let scoped_saved=scoped.db.read().await.unwrap();
    broad.db.close().await;scoped.db.close().await;drop(store);
    let broad_url=std::env::var("COMMUNITYHERO_WRITER_V51_TEST_URL").unwrap();
    broad.db=Database::postgres(&broad_url).await.unwrap();scoped.db=Database::postgres(&scoped_url).await.unwrap();
    assert_eq!(broad.db.read().await.unwrap(),broad_saved);assert_eq!(scoped.db.read().await.unwrap(),scoped_saved);
    let reopened=crate::media_artifacts::ArtifactStore::open(&cas).unwrap();
    for (run,record,artifact,bytes) in captures{
        assert_eq!(reopened.read_bytes(&artifact,128*1024*1024).unwrap(),bytes);
        for app in [&broad,&scoped]{
            let saved=app.db.read().await.unwrap();let job=crate::row(&saved,"jobs",&run).unwrap();
            assert_eq!(crate::runtime_paid_result::resolve_from(&reopened,"likeavto","LikeAvto",Some(&run),"assistant",&job["retainedEvidence"][0]).unwrap(),record);
            let (_,changed)=app.recover_completed_preparation(&run,job["completedRecovery"]["planDigest"].as_str().unwrap(),
                &job["preparationStages"]["reviewChunks"]["profile"],&crate::now()).await.unwrap();assert!(!changed);
            assert_eq!(app.db.read().await.unwrap(),saved,"restart replay must not rewrite history");
        }
    }
    eprintln!("r3_workload_report {}",json!({"selector":"postgres_r3_final_recovery_workload_100_1000_5000_actual_app_pair",
        "measuredPairs":3,"reports":reports,"restartReadbackAndPaidReferenceResolution":true,"status":"OBSERVED_TEST_ONLY"}));
    broad.db.close().await;scoped.db.close().await;
}
